name: Run Backtest

on:
  workflow_dispatch:

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run main
        run: |
          printf "6\n\n\n100\n300\ny\n\n" | python main.py